// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ch/websoft/taxulator/shared/data/taxrate.proto

package ch.websoft.taxulator.shared.data;

public final class TaxrateListProtos {
  private TaxrateListProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TaxrateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ch.websoft.taxulator.shared.data.Taxrate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double treshold = 1;</code>
     */
    boolean hasTreshold();
    /**
     * <code>required double treshold = 1;</code>
     */
    double getTreshold();

    /**
     * <code>required double step = 2;</code>
     */
    boolean hasStep();
    /**
     * <code>required double step = 2;</code>
     */
    double getStep();
  }
  /**
   * Protobuf type {@code ch.websoft.taxulator.shared.data.Taxrate}
   */
  public  static final class Taxrate extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ch.websoft.taxulator.shared.data.Taxrate)
      TaxrateOrBuilder {
    // Use Taxrate.newBuilder() to construct.
    private Taxrate(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private Taxrate() {
      treshold_ = 0D;
      step_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Taxrate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              treshold_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              step_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.websoft.taxulator.shared.data.TaxrateListProtos.internal_static_ch_websoft_taxulator_shared_data_Taxrate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.websoft.taxulator.shared.data.TaxrateListProtos.internal_static_ch_websoft_taxulator_shared_data_Taxrate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.class, ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder.class);
    }

    private int bitField0_;
    public static final int TRESHOLD_FIELD_NUMBER = 1;
    private double treshold_;
    /**
     * <code>required double treshold = 1;</code>
     */
    public boolean hasTreshold() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double treshold = 1;</code>
     */
    public double getTreshold() {
      return treshold_;
    }

    public static final int STEP_FIELD_NUMBER = 2;
    private double step_;
    /**
     * <code>required double step = 2;</code>
     */
    public boolean hasStep() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double step = 2;</code>
     */
    public double getStep() {
      return step_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTreshold()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStep()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, treshold_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, step_);
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, treshold_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, step_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ch.websoft.taxulator.shared.data.Taxrate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ch.websoft.taxulator.shared.data.Taxrate)
        ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.websoft.taxulator.shared.data.TaxrateListProtos.internal_static_ch_websoft_taxulator_shared_data_Taxrate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.websoft.taxulator.shared.data.TaxrateListProtos.internal_static_ch_websoft_taxulator_shared_data_Taxrate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.class, ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder.class);
      }

      // Construct using ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        treshold_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        step_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.websoft.taxulator.shared.data.TaxrateListProtos.internal_static_ch_websoft_taxulator_shared_data_Taxrate_descriptor;
      }

      public ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate getDefaultInstanceForType() {
        return ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.getDefaultInstance();
      }

      public ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate build() {
        ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate buildPartial() {
        ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate result = new ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.treshold_ = treshold_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.step_ = step_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate) {
          return mergeFrom((ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate other) {
        if (other == ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.getDefaultInstance()) return this;
        if (other.hasTreshold()) {
          setTreshold(other.getTreshold());
        }
        if (other.hasStep()) {
          setStep(other.getStep());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTreshold()) {
          return false;
        }
        if (!hasStep()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double treshold_ ;
      /**
       * <code>required double treshold = 1;</code>
       */
      public boolean hasTreshold() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double treshold = 1;</code>
       */
      public double getTreshold() {
        return treshold_;
      }
      /**
       * <code>required double treshold = 1;</code>
       */
      public Builder setTreshold(double value) {
        bitField0_ |= 0x00000001;
        treshold_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double treshold = 1;</code>
       */
      public Builder clearTreshold() {
        bitField0_ = (bitField0_ & ~0x00000001);
        treshold_ = 0D;
        onChanged();
        return this;
      }

      private double step_ ;
      /**
       * <code>required double step = 2;</code>
       */
      public boolean hasStep() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double step = 2;</code>
       */
      public double getStep() {
        return step_;
      }
      /**
       * <code>required double step = 2;</code>
       */
      public Builder setStep(double value) {
        bitField0_ |= 0x00000002;
        step_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double step = 2;</code>
       */
      public Builder clearStep() {
        bitField0_ = (bitField0_ & ~0x00000002);
        step_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ch.websoft.taxulator.shared.data.Taxrate)
    }

    // @@protoc_insertion_point(class_scope:ch.websoft.taxulator.shared.data.Taxrate)
    private static final ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate();
    }

    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<Taxrate> PARSER =
        new com.google.protobuf.AbstractParser<Taxrate>() {
      public Taxrate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Taxrate(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Taxrate> getParserForType() {
      return PARSER;
    }

    public ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TaxrateListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ch.websoft.taxulator.shared.data.TaxrateList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
     */
    java.util.List<ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate> 
        getTaxrateList();
    /**
     * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
     */
    ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate getTaxrate(int index);
    /**
     * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
     */
    int getTaxrateCount();
    /**
     * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
     */
    java.util.List<? extends ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateOrBuilder> 
        getTaxrateOrBuilderList();
    /**
     * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
     */
    ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateOrBuilder getTaxrateOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ch.websoft.taxulator.shared.data.TaxrateList}
   */
  public  static final class TaxrateList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ch.websoft.taxulator.shared.data.TaxrateList)
      TaxrateListOrBuilder {
    // Use TaxrateList.newBuilder() to construct.
    private TaxrateList(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private TaxrateList() {
      taxrate_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaxrateList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                taxrate_ = new java.util.ArrayList<ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate>();
                mutable_bitField0_ |= 0x00000001;
              }
              taxrate_.add(input.readMessage(ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          taxrate_ = java.util.Collections.unmodifiableList(taxrate_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ch.websoft.taxulator.shared.data.TaxrateListProtos.internal_static_ch_websoft_taxulator_shared_data_TaxrateList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ch.websoft.taxulator.shared.data.TaxrateListProtos.internal_static_ch_websoft_taxulator_shared_data_TaxrateList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList.class, ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList.Builder.class);
    }

    public static final int TAXRATE_FIELD_NUMBER = 1;
    private java.util.List<ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate> taxrate_;
    /**
     * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
     */
    public java.util.List<ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate> getTaxrateList() {
      return taxrate_;
    }
    /**
     * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
     */
    public java.util.List<? extends ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateOrBuilder> 
        getTaxrateOrBuilderList() {
      return taxrate_;
    }
    /**
     * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
     */
    public int getTaxrateCount() {
      return taxrate_.size();
    }
    /**
     * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
     */
    public ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate getTaxrate(int index) {
      return taxrate_.get(index);
    }
    /**
     * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
     */
    public ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateOrBuilder getTaxrateOrBuilder(
        int index) {
      return taxrate_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getTaxrateCount(); i++) {
        if (!getTaxrate(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < taxrate_.size(); i++) {
        output.writeMessage(1, taxrate_.get(i));
      }
      unknownFields.writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < taxrate_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, taxrate_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ch.websoft.taxulator.shared.data.TaxrateList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ch.websoft.taxulator.shared.data.TaxrateList)
        ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ch.websoft.taxulator.shared.data.TaxrateListProtos.internal_static_ch_websoft_taxulator_shared_data_TaxrateList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ch.websoft.taxulator.shared.data.TaxrateListProtos.internal_static_ch_websoft_taxulator_shared_data_TaxrateList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList.class, ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList.Builder.class);
      }

      // Construct using ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTaxrateFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (taxrateBuilder_ == null) {
          taxrate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          taxrateBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ch.websoft.taxulator.shared.data.TaxrateListProtos.internal_static_ch_websoft_taxulator_shared_data_TaxrateList_descriptor;
      }

      public ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList getDefaultInstanceForType() {
        return ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList.getDefaultInstance();
      }

      public ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList build() {
        ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList buildPartial() {
        ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList result = new ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList(this);
        int from_bitField0_ = bitField0_;
        if (taxrateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            taxrate_ = java.util.Collections.unmodifiableList(taxrate_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.taxrate_ = taxrate_;
        } else {
          result.taxrate_ = taxrateBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList) {
          return mergeFrom((ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList other) {
        if (other == ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList.getDefaultInstance()) return this;
        if (taxrateBuilder_ == null) {
          if (!other.taxrate_.isEmpty()) {
            if (taxrate_.isEmpty()) {
              taxrate_ = other.taxrate_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTaxrateIsMutable();
              taxrate_.addAll(other.taxrate_);
            }
            onChanged();
          }
        } else {
          if (!other.taxrate_.isEmpty()) {
            if (taxrateBuilder_.isEmpty()) {
              taxrateBuilder_.dispose();
              taxrateBuilder_ = null;
              taxrate_ = other.taxrate_;
              bitField0_ = (bitField0_ & ~0x00000001);
              taxrateBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTaxrateFieldBuilder() : null;
            } else {
              taxrateBuilder_.addAllMessages(other.taxrate_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getTaxrateCount(); i++) {
          if (!getTaxrate(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate> taxrate_ =
        java.util.Collections.emptyList();
      private void ensureTaxrateIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          taxrate_ = new java.util.ArrayList<ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate>(taxrate_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate, ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder, ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateOrBuilder> taxrateBuilder_;

      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public java.util.List<ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate> getTaxrateList() {
        if (taxrateBuilder_ == null) {
          return java.util.Collections.unmodifiableList(taxrate_);
        } else {
          return taxrateBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public int getTaxrateCount() {
        if (taxrateBuilder_ == null) {
          return taxrate_.size();
        } else {
          return taxrateBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate getTaxrate(int index) {
        if (taxrateBuilder_ == null) {
          return taxrate_.get(index);
        } else {
          return taxrateBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public Builder setTaxrate(
          int index, ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate value) {
        if (taxrateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaxrateIsMutable();
          taxrate_.set(index, value);
          onChanged();
        } else {
          taxrateBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public Builder setTaxrate(
          int index, ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder builderForValue) {
        if (taxrateBuilder_ == null) {
          ensureTaxrateIsMutable();
          taxrate_.set(index, builderForValue.build());
          onChanged();
        } else {
          taxrateBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public Builder addTaxrate(ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate value) {
        if (taxrateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaxrateIsMutable();
          taxrate_.add(value);
          onChanged();
        } else {
          taxrateBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public Builder addTaxrate(
          int index, ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate value) {
        if (taxrateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTaxrateIsMutable();
          taxrate_.add(index, value);
          onChanged();
        } else {
          taxrateBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public Builder addTaxrate(
          ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder builderForValue) {
        if (taxrateBuilder_ == null) {
          ensureTaxrateIsMutable();
          taxrate_.add(builderForValue.build());
          onChanged();
        } else {
          taxrateBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public Builder addTaxrate(
          int index, ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder builderForValue) {
        if (taxrateBuilder_ == null) {
          ensureTaxrateIsMutable();
          taxrate_.add(index, builderForValue.build());
          onChanged();
        } else {
          taxrateBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public Builder addAllTaxrate(
          java.lang.Iterable<? extends ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate> values) {
        if (taxrateBuilder_ == null) {
          ensureTaxrateIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, taxrate_);
          onChanged();
        } else {
          taxrateBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public Builder clearTaxrate() {
        if (taxrateBuilder_ == null) {
          taxrate_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          taxrateBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public Builder removeTaxrate(int index) {
        if (taxrateBuilder_ == null) {
          ensureTaxrateIsMutable();
          taxrate_.remove(index);
          onChanged();
        } else {
          taxrateBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder getTaxrateBuilder(
          int index) {
        return getTaxrateFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateOrBuilder getTaxrateOrBuilder(
          int index) {
        if (taxrateBuilder_ == null) {
          return taxrate_.get(index);  } else {
          return taxrateBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public java.util.List<? extends ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateOrBuilder> 
           getTaxrateOrBuilderList() {
        if (taxrateBuilder_ != null) {
          return taxrateBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(taxrate_);
        }
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder addTaxrateBuilder() {
        return getTaxrateFieldBuilder().addBuilder(
            ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.getDefaultInstance());
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder addTaxrateBuilder(
          int index) {
        return getTaxrateFieldBuilder().addBuilder(
            index, ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.getDefaultInstance());
      }
      /**
       * <code>repeated .ch.websoft.taxulator.shared.data.Taxrate taxrate = 1;</code>
       */
      public java.util.List<ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder> 
           getTaxrateBuilderList() {
        return getTaxrateFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate, ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder, ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateOrBuilder> 
          getTaxrateFieldBuilder() {
        if (taxrateBuilder_ == null) {
          taxrateBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate, ch.websoft.taxulator.shared.data.TaxrateListProtos.Taxrate.Builder, ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateOrBuilder>(
                  taxrate_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          taxrate_ = null;
        }
        return taxrateBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ch.websoft.taxulator.shared.data.TaxrateList)
    }

    // @@protoc_insertion_point(class_scope:ch.websoft.taxulator.shared.data.TaxrateList)
    private static final ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList();
    }

    public static ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<TaxrateList> PARSER =
        new com.google.protobuf.AbstractParser<TaxrateList>() {
      public TaxrateList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TaxrateList(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TaxrateList> getParserForType() {
      return PARSER;
    }

    public ch.websoft.taxulator.shared.data.TaxrateListProtos.TaxrateList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ch_websoft_taxulator_shared_data_Taxrate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ch_websoft_taxulator_shared_data_Taxrate_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ch_websoft_taxulator_shared_data_TaxrateList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ch_websoft_taxulator_shared_data_TaxrateList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n.ch/websoft/taxulator/shared/data/taxra" +
      "te.proto\022 ch.websoft.taxulator.shared.da" +
      "ta\")\n\007Taxrate\022\020\n\010treshold\030\001 \002(\001\022\014\n\004step\030" +
      "\002 \002(\001\"I\n\013TaxrateList\022:\n\007taxrate\030\001 \003(\0132)." +
      "ch.websoft.taxulator.shared.data.Taxrate" +
      "B\023B\021TaxrateListProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ch_websoft_taxulator_shared_data_Taxrate_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ch_websoft_taxulator_shared_data_Taxrate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ch_websoft_taxulator_shared_data_Taxrate_descriptor,
        new java.lang.String[] { "Treshold", "Step", });
    internal_static_ch_websoft_taxulator_shared_data_TaxrateList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ch_websoft_taxulator_shared_data_TaxrateList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ch_websoft_taxulator_shared_data_TaxrateList_descriptor,
        new java.lang.String[] { "Taxrate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
